# Generated by Django 4.1.4 on 2023-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('nameRu', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('trailer_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('countryRu', models.CharField(max_length=255)),
                ('genreRu', models.CharField(max_length=255)),
                ('filmDirector', models.CharField(max_length=255)),
                ('screenWriter', models.CharField(max_length=255)),
                ('budjet', models.IntegerField()),
                ('moneyUsa', models.IntegerField()),
                ('moneyTotal', models.IntegerField()),
                ('premier', models.DateField()),
                ('premierRu', models.DateField()),
                ('age', models.IntegerField()),
                ('time', models.IntegerField()),
                ('trailer_file', models.FileField(default=None, null=True, upload_to='trailers')),
            ],
        ),
    ]
