# Generated by Django 4.1.4 on 2022-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField(max_length=4)),
                ('country', models.CharField(max_length=255)),
                ('countryRu', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('genreRu', models.CharField(max_length=255)),
                ('filmDirector', models.CharField(max_length=255)),
                ('filmDirectorRu', models.CharField(max_length=255)),
                ('screenWriter', models.CharField(max_length=255)),
                ('screenWriterRu', models.CharField(max_length=255)),
                ('budjet', models.IntegerField()),
                ('moneyUsa', models.IntegerField()),
                ('moneyTotal', models.IntegerField()),
                ('premier', models.DateField()),
                ('premierRu', models.DateField()),
                ('age', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
