# Generated by Django 4.1.4 on 2022-12-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_movie_title_movie_name_movie_nameru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='country',
            new_name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='filmDirectorRu',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screenWriterRu',
        ),
    ]
