# Generated by Django 4.1.4 on 2023-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_country_movie_trailer_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_file',
            field=models.FileField(default='none', null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
